server:
  port: 9110


spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      db1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/technology-services?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
      db2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://117.34.111.236:3306/technology-services?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    freemarker:
      cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: file:D:\\vehicle-technical-file\\src\\main\\resources\\static,classpath:/static/

#mybatis-plus配置
mybatis-plus:
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

